name: Fanless Environment Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my_fanless_image .

      - name: Run tests in fanless environment
        run: docker run my_fanless_image python test_fan_reaction.py

